[2023-08-14T11:15:00.868+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hp_pipeline.write_db manual__2023-08-14T09:13:42.250908+00:00 [queued]>
[2023-08-14T11:15:00.873+0200] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hp_pipeline.write_db manual__2023-08-14T09:13:42.250908+00:00 [queued]>
[2023-08-14T11:15:00.873+0200] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-14T11:15:00.888+0200] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): write_db> on 2023-08-14 09:13:42.250908+00:00
[2023-08-14T11:15:00.892+0200] {standard_task_runner.py:57} INFO - Started process 464744 to run task
[2023-08-14T11:15:00.896+0200] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'hp_pipeline', 'write_db', 'manual__2023-08-14T09:13:42.250908+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/hp_pipeline.py', '--cfg-path', '/tmp/tmpz6th2l5r']
[2023-08-14T11:15:00.897+0200] {standard_task_runner.py:85} INFO - Job 31: Subtask write_db
[2023-08-14T11:15:00.931+0200] {task_command.py:410} INFO - Running <TaskInstance: hp_pipeline.write_db manual__2023-08-14T09:13:42.250908+00:00 [running]> on host akhilesh-ThinkPad-E14-Gen-3
[2023-08-14T11:15:00.984+0200] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='hp_pipeline' AIRFLOW_CTX_TASK_ID='write_db' AIRFLOW_CTX_EXECUTION_DATE='2023-08-14T09:13:42.250908+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-14T09:13:42.250908+00:00'
[2023-08-14T11:15:00.986+0200] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-14T11:15:00.986+0200] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /home/akhilesh/personal/Assignment/Scripts/ && source /home/akhilesh/py39/bin/activate && python load.py']
[2023-08-14T11:15:00.998+0200] {subprocess.py:86} INFO - Output:
[2023-08-14T11:15:01.264+0200] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-08-14T11:15:01.264+0200] {subprocess.py:93} INFO -   File "/home/akhilesh/personal/Assignment/Scripts/load.py", line 13, in <module>
[2023-08-14T11:15:01.264+0200] {subprocess.py:93} INFO -     df = pd.read_csv('/home/akhilesh/personal/Assignment/data/hp_oltis_sanctioned_budget.csv')
[2023-08-14T11:15:01.264+0200] {subprocess.py:93} INFO -   File "/home/akhilesh/py39/lib/python3.9/site-packages/pandas/util/_decorators.py", line 211, in wrapper
[2023-08-14T11:15:01.265+0200] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2023-08-14T11:15:01.265+0200] {subprocess.py:93} INFO -   File "/home/akhilesh/py39/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
[2023-08-14T11:15:01.266+0200] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2023-08-14T11:15:01.266+0200] {subprocess.py:93} INFO -   File "/home/akhilesh/py39/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
[2023-08-14T11:15:01.266+0200] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2023-08-14T11:15:01.267+0200] {subprocess.py:93} INFO -   File "/home/akhilesh/py39/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 605, in _read
[2023-08-14T11:15:01.267+0200] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2023-08-14T11:15:01.267+0200] {subprocess.py:93} INFO -   File "/home/akhilesh/py39/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
[2023-08-14T11:15:01.267+0200] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2023-08-14T11:15:01.267+0200] {subprocess.py:93} INFO -   File "/home/akhilesh/py39/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
[2023-08-14T11:15:01.267+0200] {subprocess.py:93} INFO -     self.handles = get_handle(
[2023-08-14T11:15:01.267+0200] {subprocess.py:93} INFO -   File "/home/akhilesh/py39/lib/python3.9/site-packages/pandas/io/common.py", line 856, in get_handle
[2023-08-14T11:15:01.267+0200] {subprocess.py:93} INFO -     handle = open(
[2023-08-14T11:15:01.267+0200] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/home/akhilesh/personal/Assignment/data/hp_oltis_sanctioned_budget.csv'
[2023-08-14T11:15:01.319+0200] {subprocess.py:97} INFO - Command exited with return code 1
[2023-08-14T11:15:01.328+0200] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/akhilesh/py39/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-08-14T11:15:01.331+0200] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=hp_pipeline, task_id=write_db, execution_date=20230814T091342, start_date=20230814T091500, end_date=20230814T091501
[2023-08-14T11:15:01.345+0200] {standard_task_runner.py:104} ERROR - Failed to execute job 31 for task write_db (Bash command failed. The command returned a non-zero exit code 1.; 464744)
[2023-08-14T11:15:01.389+0200] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-14T11:15:01.405+0200] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
